import {
  MessageSquareText, CalendarCheck2, Briefcase,
  GraduationCap, HeartHandshake, ShoppingBag, ClipboardList, Users, Sparkles,
  Pen , PanelsRightBottom , Clock10 , UserRoundCheck , User2 , UserCircle2Icon
} from "lucide-react";


const templatesCategory = [
    {
    id : "cf001",
    name: "Custom Form",
    description: "Start from Blank",
    tag: "Custom",
    cover: "from-[#4f8a9h] to-[#28252f]",
    icon: Pen,
  },
      {
    id : "ic001",
    name: "Influencer Card",
    description: "Engage Your Audience",
    tag: "Influencers",
    cover: "from-[#1f7a8d] to-[42c4m3b]",
    icon: PanelsRightBottom,
  },
      {
    id : "ic002",
    name: "Profile Card",
    description: "Showcase Your Work",
    tag: "Influencers",
    cover: "from-[#f2a93j] to-[#e3433b]",
    icon: UserRoundCheck,
  },
      {
    id : "sf001",
    name: "Schedule Form",
    description: "Pin Your Next move",
    tag: "Schedule Timer",
    cover: "from-[#h3903f] to-[#6f3f98]",
    icon: Clock10,
  },
      {
    id : "ic003",
    name: "Social's Card",
    description: "Make your Presence Noticeble",
    tag: "Influencers",
    cover: "from-[#4a4b4f] to-[#4c8c2a]",
    icon: UserCircle2Icon,
  },
      {
    id : "wf001",
    name: "WaitListing Page",
    description: "Make Your Next Launch Big",
    tag: "WaitList Form",
    cover: "from-[#8br43] to-[#4c2]",
    icon: Sparkles,
  },
  { 
    id : "01",
    name: "Customer Feedback Survey",
    description: "Rate, review, and tell us how we're doing",
    tag: "Feedback",
    cover: "from-[#f2a93b] to-[#e8833b]",
    icon: MessageSquareText,
  },
  { 
    id : "02",
    name: "Event RSVP",
    description: "Collect guest counts and dietary notes",
    tag: "Events",
    cover: "from-[#6f9a8d] to-[#2c4a3b]",
    icon: CalendarCheck2,
  },
  { 
    id : "03",
    name: "Job Application",
    description: "Resume, portfolio link, and screening questions",
    tag: "HR",
    cover: "from-[#c9603f] to-[#7a3a2c]",
    icon: Briefcase,
  },
  {
    id : "04",
    name: "Course Enrollment",
    description: "Sign students up with prerequisites check",
    tag: "Education",
    cover: "from-[#3b6b8f] to-[#1f3b52]",
    icon: GraduationCap,
  },
  {
    id : "05",
    name: "Volunteer Sign-up",
    description: "Match volunteers to shifts and skills",
    tag: "Nonprofit",
    cover: "from-[#8a9b4f] to-[#4d5c2a]",
    icon: HeartHandshake,
  },
  {
    id : "06",
    name: "Product Order Form",
    description: "Quantities, variants, and delivery details",
    tag: "Orders",
    cover: "from-[#d9a441] to-[#a5741f]",
    icon: ShoppingBag,
  },
  {
    id : "07",
    name: "Employee Onboarding",
    description: "Documents, IT setup, and team intros",
    tag: "HR",
    cover: "from-[#5c6b60] to-[#2c4a3b]",
    icon: Users,
  },
  {
    id : "08",
    name: "Project Intake",
    description: "Scope, timeline, and budget questions",
    tag: "Operations",
    cover: "from-[#b3703f] to-[#6b3f22]",
    icon: ClipboardList,
  },
  {
    id : "09",
    name: "Community Survey",
    description: "Gather local input on new initiatives",
    tag: "Nonprofit",
    cover: "from-[#4f8a7a] to-[#28453c]",
    icon: Sparkles,
  },
];

export default templatesCategory;